# Dockerfile.backend
FROM python:3.10-slim

# Evita que Python escriba archivos .pyc y fuerza el output en la terminal
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar dependencias del sistema necesarias para compilar algunas librerías
RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2-dev \
    libxslt-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar e instalar los requerimientos
COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=1000 torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

# Descargar el modelo de NLP de spaCy
 

# Copiar el código fuente
COPY src/ ./src/

# Copiar el modelo Word2Vec si existe (puede no existir en primera ejecución)
COPY src/w2v_futbol.mode[l]   2>/dev/null 

# Directorio de trabajo para que funcionen los imports relativos
WORKDIR /app/src

EXPOSE 8000

CMD ["uvicorn", "infrastructure.api:app", "--host", "0.0.0.0", "--port", "8000"]